- name: Base Configuration
  hosts: frontends:apps:appdbs
  gather_facts: true
  become: true
  roles:
    - name: base

- name: deploy haproxy
  hosts: frontends
  gather_facts: false
  become: true
  roles:
    - name: haproxy

- name: deploy tomcat
  hosts: apps
  gather_facts: false
  become: true
  roles:
    - name: tomcat

- name: Install and start postgres
  hosts: appdbs
  gather_facts: false
  become: true
  roles:
    - geerlingguy.postgresql