---

# TODO: need to check the k8_facts for an already existing htpasswd to see if
# we need to even create this

- name: Create the htpasswd file
  htpasswd:
    path: "{{ HTPasswd.location }}"
    state: present
    create: yes
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    owner: root
    group: root
    mode: 0640
  loop: "{{ HTPasswd.users }}"
  no_log: true

- name: Slurp the file so we can base64 encode it
  slurp:
    src: "{{ HTPasswd.location }}"
  register: htpasswd_slurp

- name: Create the htpasswd Secret
  k8s:
    api_key: "{{ token }}"
    state: present
    definition: "{{ lookup('template','secret.yml.j2') | from_yaml }}"
  vars:
    name: "{{ HTPasswd.secret_name }}"
    namespace: "{{ HTPasswd.namespace }}"
    attribute: "htpasswd"
    value: "{{ htpasswd_slurp['content'] }}"
    type: "generic"

- name: Create the OAuth configuraiton
  k8s: 
    api_key: "{{ token }}"
    state: present
    definition: "{{ lookup('template','htpasswd.yml.j2') | from_yaml }}"
  vars:
    secret_name: "{{ HTPasswd.secret_name }}"
#  command: >- 
#    oc apply -f-
#  args:
#    stdin: "{{ lookup('template','secret.yml.j2') | to_json }}"
#  vars:
#    name: "{{ HTPasswd.secret_name }}"
#    namespace: "{{ HTPasswd.namespace }}"
#    attribute: "htpasswd"
#    value: "{{ htpasswd_slurp }}"